
// Generated by Akka gRPC. DO NOT EDIT.
package sn.atos.wordline.nsbf.filetranfertgrpc.srv;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;


public interface FileTransfertManager {
  
  
  java.util.concurrent.CompletionStage<sn.atos.wordline.nsbf.filetranfertgrpc.srv.PostFileActionPerformed> postFile(sn.atos.wordline.nsbf.filetranfertgrpc.srv.filePart in);
  

  static String name = "FileTransfertManager.FileTransfertManager";

  public static class Serializers {
    
      public static ProtobufSerializer<sn.atos.wordline.nsbf.filetranfertgrpc.srv.filePart> filePartSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.nsbf.filetranfertgrpc.srv.filePart.class);
    
      public static ProtobufSerializer<sn.atos.wordline.nsbf.filetranfertgrpc.srv.PostFileActionPerformed> PostFileActionPerformedSerializer = new GoogleProtobufSerializer<>(sn.atos.wordline.nsbf.filetranfertgrpc.srv.PostFileActionPerformed.class);
    
  }
}
