// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package sn.atos.wordline.nsbf.filetranfertgrpc.srv;

public final class FileTransfert {
  private FileTransfert() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileTransfertManager_filePart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileTransfertManager_filePart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileTransfertManager_PostFileActionPerformed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileTransfertManager_PostFileActionPerformed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nproj.proto\022\024FileTransfertManager\"\031\n\010fi" +
      "lePart\022\r\n\005chunk\030\001 \001(\014\"R\n\027PostFileActionP" +
      "erformed\022\024\n\014errorMessage\030\001 \001(\t\022\020\n\010hasErr" +
      "or\030\002 \001(\010\022\017\n\007message\030\003 \001(\t2s\n\024FileTransfe" +
      "rtManager\022[\n\010PostFile\022\036.FileTransfertMan" +
      "ager.filePart\032-.FileTransfertManager.Pos" +
      "tFileActionPerformed\"\000B=\n*sn.atos.wordli" +
      "ne.nsbf.filetranfertgrpc.srvB\rFileTransf" +
      "ertP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FileTransfertManager_filePart_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileTransfertManager_filePart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileTransfertManager_filePart_descriptor,
        new java.lang.String[] { "Chunk", });
    internal_static_FileTransfertManager_PostFileActionPerformed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileTransfertManager_PostFileActionPerformed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileTransfertManager_PostFileActionPerformed_descriptor,
        new java.lang.String[] { "ErrorMessage", "HasError", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
