
// Generated by Akka gRPC. DO NOT EDIT.
package sn.atos.wordline.nsbf.filetranfertgrpc.srv;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class FileTransfertManagerClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer postFile(sn.atos.wordline.nsbf.filetranfertgrpc.srv.filePart) if possible.
     */
    
      public SingleResponseRequestBuilder<sn.atos.wordline.nsbf.filetranfertgrpc.srv.filePart, sn.atos.wordline.nsbf.filetranfertgrpc.srv.PostFileActionPerformed> postFile()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer postFileinfo(sn.atos.wordline.nsbf.filetranfertgrpc.srv.fileInfo) if possible.
     */
    
      public SingleResponseRequestBuilder<sn.atos.wordline.nsbf.filetranfertgrpc.srv.fileInfo, sn.atos.wordline.nsbf.filetranfertgrpc.srv.PostFileInfoActionPerformed> postFileinfo()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}
