// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package sn.atos.wordline.nsbf.filetranfertgrpc.srv;

public interface fileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileTransfertManager.fileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identifiant = 1;</code>
   */
  java.lang.String getIdentifiant();
  /**
   * <code>string identifiant = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifiantBytes();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>string fileName = 3;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int32 totalblocNumber = 4;</code>
   */
  int getTotalblocNumber();
}
