// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package sn.atos.wordline.nsbf.filetranfertgrpc.srv;

public interface filePartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileTransfertManager.filePart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes chunk = 1;</code>
   */
  com.google.protobuf.ByteString getChunk();
}
