// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package sn.atos.wordline.nsbf.filetranfertgrpc.srv;

public interface PostFileInfoActionPerformedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileTransfertManager.PostFileInfoActionPerformed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errorMessage = 1;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>bool hasError = 2;</code>
   */
  boolean getHasError();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
